// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUp0dSyVMDpcKFcHciGnpGBkGQiCJ-nfg',
    appId: '1:523938747996:web:d7a35a77db83502679f899',
    messagingSenderId: '523938747996',
    projectId: 'faculty-purpose-bb50a',
    authDomain: 'faculty-purpose-bb50a.firebaseapp.com',
    storageBucket: 'faculty-purpose-bb50a.firebasestorage.app',
    measurementId: 'G-STV7Z1MCVX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDy4X5wISPSqLPvNC3K_3Ijk4NkEYArC-k',
    appId: '1:523938747996:android:54be19ee14e13a4479f899',
    messagingSenderId: '523938747996',
    projectId: 'faculty-purpose-bb50a',
    storageBucket: 'faculty-purpose-bb50a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0FGrhq26gAcTgOqruxqbwSF4YmWvvKUo',
    appId: '1:523938747996:ios:200b620cfe7e22c279f899',
    messagingSenderId: '523938747996',
    projectId: 'faculty-purpose-bb50a',
    storageBucket: 'faculty-purpose-bb50a.firebasestorage.app',
    iosBundleId: 'com.example.myproject',
  );
}
